site_name: Wiki Critique
theme:
  name: material
  logo: img/boussole.png
  favicon: img/boussole_noire.ico
  font:
    text: Averia Serif Libre
  palette:
    
    # Palette toggle for light mode
    - scheme: default
      primary: black
      accent: amber
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  custom_dir: docs/stylesheets

extra_css:
  - stylesheets/custom.css

extra_javascript:
  - js/readingTime.js

markdown_extensions: 
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Introduction: index.md
  - Contre-arguments: contre_arguments.md
  - Évènements historiques majeurs peu connus: evenements.md
  - Personnalités majeures peu connues: personnalites.md
  - Courants de pensée: courants.md
  - Notions et vocabulaire: notions.md