site_name: Wiki Critique
theme:
  name: material
  logo: img/boussole.png
  favicon: img/boussole_noire.ico
  font:
    text: Averia Serif Libre
  palette:
    
    # Palette toggle for light mode
    - scheme: default
      primary: black
      accent: amber
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  custom_dir: docs/stylesheets

extra_css:
  - stylesheets/custom.css

nav:
  - Introduction: index.md
  - Personnalités: personnalites.md
  - Courants de pensée: courants.md
  - Contre-arguments: contre_arguments.md
  - Évènements historiques majeurs occultés: evenements_historiques.md
  - Notions et vocabulaire: notions.md